# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-01-08 17:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('skill', models.TextField()),
                ('twitter_address', models.URLField(blank=True)),
                ('slack_address', models.URLField(blank=True)),
                ('skype_address', models.URLField(blank=True)),
                ('github_repo', models.URLField(blank=True)),
                ('profile_pic', models.ImageField(blank=True, upload_to='./media/profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
