# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-01-24 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hireme', '0002_auto_20190109_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
