# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-01-24 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hireme', '0003_userprofileinfo_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='image',
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
